other test

diff --git a/.github/workflows/check_on_branch.yml b/.github/workflows/check_on_branch.yml
--- a/.github/workflows/check_on_branch.yml
+++ b/.github/workflows/check_on_branch.yml
@@ -84,12 +84,10 @@ jobs:
 
       - name: Check documentation
         run: |
-          x <- checklist::check_documentation()
-          echo "docu=x" >> $GITHUB_ENV
-        shell: Rscript {0}
+          Rscript --no-save --no-restore -e 'checklist::check_documentation()'
       - name: give documentation error
-        if: ${{ env.docu$fail }}
-        run: echo '::error ::${{ env.docu$fail }}'
+        if: [ $? -ne 0 ]
+        run: echo '::error ::${{ env.fail }}'
 
       - name: Check description
         run: checklist::check_description()
