and remove bash script again, seems superfluous

diff --git a/.github/workflows/check_on_branch.yml b/.github/workflows/check_on_branch.yml
--- a/.github/workflows/check_on_branch.yml
+++ b/.github/workflows/check_on_branch.yml
@@ -93,20 +93,15 @@ jobs:
 
       - name: Check description
         run: |
-          Rscript --no-save --no-restore -e 'checklist::check_description()'
-          Rscript --no-save --no-restore -e 'if(checklist::check_description()$fail) {  stop("Error in the desciption file, please check the error message above.") }'
-          if [ $? -ne 0 ]; then
-            echo '\nError in the desciption file, please check the error message above.\n';
-            exit 1
-          fi
-        shell: bash
-      - name: Check description2
-        run: |
-          Rscript --no-save --no-restore -e 'if(checklist::check_description()$fail) {stop("Error!!!")}'
-          if [ $? -ne 0 ]; then
-            echo '\nError in the desciption file, please check the error message above.\n';
-            exit 1
-          fi
+          checklist::check_description()
+          if(checklist::check_description()$fail) {
+            stop("Error in the desciption file, please check the error message above.")
+          }
+          #if [ $? -ne 0 ]; then
+            #echo '\nError in the desciption file, please check the error message above.\n';
+            #exit 1
+          #fi
+        shell: Rscript {0}
 
       - name: Check code coverage
         run: |
